kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-es
  namespace: {{ .Release.Namespace | quote }}
reclaimPolicy: Retain
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: es
    release: es
  name: es-data-elasticsearch-0
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      pvl: "pvl-es"
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage-es
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-es
  namespace: {{ .Release.Namespace | quote }}
  labels:
    pvl: pvl-es
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-es
  local:
    path: /data/monitoreo/elastic
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: group
          operator: In
          values:
          - monitoreo  
